### ISSUE TITLE
No threads to run command

### ISSUE THREAD

**Issue by ihdavids** [daveleroy/SublimeDebugger#101]
I am exceedingly excited to try to use your debugger pluging but have been running into a few problems. I was hoping you could point me in the right direction here. Any attempt to use the lldb adapter results in an exception. I cannot get the terminal to launch with the platform module and when I switch to the terminus plugin I run into the following exception without fail:

OS: Windows

{
	"log_info": true,
	"ui_scale": 10,
	"font_face": "Inconsolata",
	"external_terminal": "terminus"
}

Just to be sure I was on head I pulled your plugin from source:

Branch ST3 head as of today 1/3/2021
commit 85387c9334688974817361c473ce0f98ce3fd489 (HEAD -> st3, tag: st3-0.2.10, origin/st3)
Author: David <2889367+daveleroy@users.noreply.github.com>
Date:   Fri Nov 13 01:43:07 2020 -0800

    fixes issues with latest release of lldb adapter and fixes #74

I am getting the following when I click the play button in a debug session:
I have a simple application that does a printf inside main and I am trying to break on the first line.

NOTE the TRYING TO START THINGS is my little addition to the package to understand where things were going off the rails with the platform terminal.

======================================================
updating settings callback view
Settings were udpdated: reloading configuations
Settings were udpdated: reloading configuations
Settings were udpdated: reloading configuations
Settings were udpdated: reloading configuations
updating settings callback view
updating settings callback view
Settings were udpdated: reloading configuations
Settings were udpdated: reloading configuations
Settings were udpdated: reloading configuations
Settings were udpdated: reloading configuations
Settings were udpdated: reloading configuations
updating settings callback view
updating settings callback view
Settings were udpdated: reloading configuations
Settings were udpdated: reloading configuations
updating settings callback view
updating settings callback view
Settings were udpdated: reloading configuations
Settings were udpdated: reloading configuations
Starting process: ['node', 'C:\\Users\\ihdav\\AppData\\Roaming\\Sublime Text\\Packages\\Debugger/debug_adapters/lldb_util/entry.js', 'C:\\Users\\ihdav\\AppData\\Roaming\\Sublime Text\\Packages\\Debugger\\data\\debug_adapters\\vscode-lldb/extension/adapter/codelldb']
<<  {"type": "request", "command": "initialize", "seq": 1, "arguments": {"locale": "en-us", "adapterID": "python", "clientID": "sublime", "clientName": "Sublime Text", "columnsStartAt1": true, "supportsRunInTerminalRequest": true, "linesStartAt1": true, "supportsVariableType": true, "supportsVariablePaging": false, "pathFormat": "path"}}
>>  {"type":"response","request_seq":1,"success":true,"command":"initialize","body":{"exceptionBreakpointFilters":[{"default":true,"filter":"cpp_throw","label":"C++: on throw"},{"default":false,"filter":"cpp_catch","label":"C++: on catch"}],"supportTerminateDebuggee":true,"supportsCancelRequest":true,"supportsCompletionsRequest":true,"supportsConditionalBreakpoints":true,"supportsConfigurationDoneRequest":true,"supportsDataBreakpoints":true,"supportsDelayedStackTraceLoading":true,"supportsEvaluateForHovers":true,"supportsFunctionBreakpoints":true,"supportsGotoTargetsRequest":true,"supportsHitConditionalBreakpoints":true,"supportsLogPoints":true,"supportsReadMemoryRequest":true,"supportsRestartFrame":true,"supportsSetVariable":true}}
<<  {"type": "request", "command": "launch", "seq": 2, "arguments": {"type": "lldb", "request": "launch", "args": ["-arg1", "-arg2"], "name": "Dbg", "program": "C:\\Users\\ihdav\\repos\\cpptest/src/a.exe"}}
>>  {"type":"event","seq":1,"event":"initialized"}
>>  {"type":"request","seq":2,"command":"runInTerminal","arguments":{"args":["C:\\Users\\ihdav\\AppData\\Roaming\\Sublime Text\\Packages\\Debugger\\data\\debug_adapters\\vscode-lldb\\extension\\adapter\\codelldb.exe","terminal-agent","--port=61512"],"cwd":"","kind":"integrated","title":"Dbg"}}
Starting process: ['C:\\Users\\ihdav\\AppData\\Roaming\\Sublime Text\\Packages\\Debugger\\data\\debug_adapters\\vscode-lldb\\extension\\adapter\\codelldb.exe', 'terminal-agent', '--port=61512']
TRYING TO START THINGS
<<  {"type": "response", "message": null, "seq": 3, "request_seq": 2, "success": true, "command": "runInTerminal"}
<<  {"type": "request", "command": "setDataBreakpoints", "seq": 4, "arguments": {"breakpoints": []}}
<<  {"type": "request", "command": "setExceptionBreakpoints", "seq": 5, "arguments": {"filters": ["cpp_throw"]}}
<<  {"type": "request", "command": "setBreakpoints", "seq": 6, "arguments": {"source": {"path": "C:\\Users\\ihdav\\repos\\cpptest\\src\\main.cpp"}, "breakpoints": [{"line": 6}]}}
<<  {"type": "request", "command": "setFunctionBreakpoints", "seq": 7, "arguments": {"breakpoints": []}}
>>  {"type":"response","request_seq":4,"success":true,"command":"setDataBreakpoints","body":{"breakpoints":[]}}
>>  {"type":"response","request_seq":5,"success":true,"command":"setExceptionBreakpoints"}
>>  {"type":"response","request_seq":6,"success":true,"command":"setBreakpoints","body":{"breakpoints":[{"id":2,"message":"Locations: 0","verified":false}]}}
>>  {"type":"response","request_seq":7,"success":true,"command":"setFunctionBreakpoints","body":{"breakpoints":[]}}
<<  {"type": "request", "command": "configurationDone", "seq": 8, "arguments": null}
>>  {"type":"event","seq":3,"event":"output","body":{"output":"Launching: C:\\Users\\ihdav\\repos\\cpptest\\src\\a.exe -arg1 -arg2\n"}}
>>  {"type":"event","seq":4,"event":"output","body":{"output":"Launched process 16192\n"}}
>>  {"type":"response","request_seq":2,"success":true,"command":"launch"}
>>  {"type":"response","request_seq":8,"success":true,"command":"configurationDone"}
>>  {"type":"event","seq":5,"event":"continued","body":{"allThreadsContinued":true,"threadId":0}}
Traceback (most recent call last):
  File "C:\Users\ihdav\AppData\Roaming\Sublime Text\Packages\Debugger\modules\core\sublime_event_loop.py", line 13, in __call__
    self.callback(*self.args)
  File "C:\Users\ihdav\AppData\Roaming\Sublime Text\Packages\Debugger\modules\dap\client.py", line 332, in _on_continued
    self._continued(threadId, body.get('allThreadsContinued', True))
  File "C:\Users\ihdav\AppData\Roaming\Sublime Text\Packages\Debugger\modules\dap\client.py", line 339, in _continued
    self.events.on_continued_event(event)
  File "C:\Users\ihdav\AppData\Roaming\Sublime Text\Packages\Debugger\modules\debugger\debugger_session.py", line 466, in on_continued_event
    self.callstack.on_continued_event(self.client, event)
  File "C:\Users\ihdav\AppData\Roaming\Sublime Text\Packages\Debugger\modules\debugger\debugger_session.py", line 652, in on_continued_event
    self.on_selected_thread(None)
  File "C:\Users\ihdav\AppData\Roaming\Sublime Text\Packages\Debugger\modules\core\event.py", line 37, in __call__
    self.post(*data)
  File "C:\Users\ihdav\AppData\Roaming\Sublime Text\Packages\Debugger\modules\core\event.py", line 41, in post
    h.callback(*data)
  File "C:\Users\ihdav\AppData\Roaming\Sublime Text\Packages\Debugger\modules\debugger\debugger_session.py", line 63, in <lambda>
    self.callstack.on_selected_thread.add(lambda thread: self._refresh_state())
  File "C:\Users\ihdav\AppData\Roaming\Sublime Text\Packages\Debugger\modules\debugger\debugger_session.py", line 222, in _refresh_state
    thread = self.callstack.command_thread()
  File "C:\Users\ihdav\AppData\Roaming\Sublime Text\Packages\Debugger\modules\debugger\debugger_session.py", line 577, in command_thread
    raise core.Error("No threads to run command")
Debugger.modules.core.error.Error: No threads to run command
==============================================================

**Comment by daveleroy** [comment]
Re-open if you still are running into issues here
