### ISSUE TITLE
Install adapter after proxy

### ISSUE THREAD

**Issue by ngockhanhnguyen** [daveleroy/SublimeDebugger#103]
Our company network sit behind a proxy setup, and i get this log when try to install adapter:
`Failed Finished Installing adapter: <urlopen error [WinError 10060] ...`

I had set proxy in package control settings:
```
"http_proxy": "http://192.168.5.8:3128",
"https_proxy": "http://192.168.5.8:3128",
```

Additional, do you guys have plan for fix this https://github.com/daveleroy/sublime_debugger/issues/52

**Comment by daveleroy** [comment]
I'm not planning on adding support for this myself. If you or someone else wants to add support for it you are welcome to do so.
