### ISSUE TITLE
django always stop in manage.py

### ISSUE THREAD

**Issue by aztrock** [daveleroy/SublimeDebugger#142]
When run debugger with django, in the second step, always stop in manage.py, in server http: serve_forever and never out of there, if i change justMyCode: true, the debugger never finish and the controls are disabled

![image](https://user-images.githubusercontent.com/4043932/147942049-376220a0-d8eb-400a-b7cf-e05f838963ac.png)

this is the config:
```
    "debugger_configurations" : [
        {
            "name" : "Debugger",
            "request" : "launch",
            "type" : "python",
            "program": "${folder}/manage.py",
            "django": true,
            "args": [
              "runserver",
              "0.0.0.0:8000",
              "--noreload"
            ],
            "env": {
                "DEBUG": "1"
            },
            "python": "/home/aztrock/Workspace/env/bin/python",
            // "console": "integratedTerminal",
            // "console": "externalTerminal",
            "justMyCode": false,
            "showReturnValue": true,
            // "gevent": true
        }
    ]
```

**Comment by daveleroy** [comment]
This sounds more like an issue with the adapter https://github.com/microsoft/debugpy assuming vscode has the same behavior

**Comment by daveleroy** [comment]
Liked fixed by https://github.com/daveleroy/SublimeDebugger/commit/33d1a829db62b0f26dfad51b1272bfc96f8dabb1
