### ISSUE TITLE
Debugger just suddenly ends!

### ISSUE THREAD

**Issue by aashish108** [daveleroy/SublimeDebugger#172]
Hi, I tried out the debugger and it just unexpectedly ends after a short while whereas using the same configuration in VSCode it works. Not sure why it ends unexpectedly? I did not see anything noteworthy to mention in terms of errors.

Debugging a React app via the Chrome launch config.

**Comment by daveleroy** [comment]
Re-open if you are still having issues and attach a log generated with `Debugger: Show Protocol`
