### ISSUE TITLE
Unable to support two or more ${} in one line

### ISSUE THREAD

**Issue by ScreeperC** [daveleroy/SublimeDebugger#215]
I want to debug my C++ program with LLDB/GDB, but unfortunately it doesn't works when i finish the setup and the bug report is as follows
![QQ截图20230405194250](https://user-images.githubusercontent.com/94523517/230130907-98383131-617a-42e8-9450-a651bfe7f27c.png)

**Comment by daveleroy** [comment]
The code for this is here if you want to fix this https://github.com/daveleroy/sublime_debugger/blob/7c88fa6402e154f41e4db1075bd336bc539b035f/modules/dap/configuration.py#L205

or wait until I get around to it

**Comment by dongguaguaguagua** [comment]
`Sublime Text/Packages/Debugger/modules/dap/configuration.py`, change the regular expression on line 207 from `(\${(.*)})` to `(\${(\w+)})` to fix it.

**Comment by daveleroy** [comment]
Fixed here https://github.com/daveleroy/SublimeDebugger/commit/f07ac3607e68e0c1782009481fed642dad18a8bf
