### ISSUE TITLE
The location of action button bar keeps changing between Terminal Console and Variables tab

### ISSUE THREAD

**Issue by z-aki** [daveleroy/SublimeDebugger#217]
The constantly changing location of frequently accessed buttons like step over keeps changing when switching tabs. Please fix them to the bottom. Or the top if the size of the panel remains fixed.

![image](https://user-images.githubusercontent.com/39851968/235302463-9c203abb-5fe5-4f0d-b928-82f493e4c26b.png)

![image](https://user-images.githubusercontent.com/39851968/235302446-b4851ee8-42e0-4eac-8631-4ca805c4fbc2.png)

**Comment by daveleroy** [comment]
Not possible to do this if it was possible they would always be at the bottom or top
