### ISSUE TITLE
Search for build tasks in build_systems key also, instead of just debugger_tasks

### ISSUE THREAD

**Issue by z-aki** [daveleroy/SublimeDebugger#218]
In a cmake generated project, build tasks are already populated. But the extension requires a new entry. 

https://github.com/daveleroy/SublimeDebugger/blob/a933215da8101d7496e68868a692845673c3983d/modules/project.py#L230

**Comment by daveleroy** [comment]
Debugger tasks and build tasks aren't the same thing so combining them is just going to lead to cases where things are broken

**Comment by z-aki** [comment]
VSCode has pre debug build tasks

**Comment by daveleroy** [comment]
Thats why debugger_tasks exists but they aren't the same as build_systems and aren't run the same and don't support the same features
