### ISSUE TITLE
Are configurations in .sublime-workspace supported?

### ISSUE THREAD

**Issue by z-aki** [daveleroy/SublimeDebugger#219]
Between a configuration set in a sublime-project file that gets overwritten by cmake and global settings that is visible everywhere, I suppose workspace files is a good compromise.

**Comment by daveleroy** [comment]
Why is your sublime-project file being overridden that seems weird. There is no api to work with sublime-workspace files and I don't think they are supposed to be hand edited.

**Comment by z-aki** [comment]
cmake's sublime text generator works this way.
