### ISSUE TITLE
`debugger_compounds` purpose

### ISSUE THREAD

**Issue by yaroslavyaroslav** [daveleroy/SublimeDebugger#232]
Hi, folks, thanks for great package port, I'm still trying to dig deep enough in it and can't find enough elaboration of `debugger_compounds` purpose in specific and `debugger_configurations`, `debugger_tasks` and `debugger_compounds` hierarchy in general?

As I can see in `sublime-settings` it's a composition of some strings, the one that reflects either tasks or configurations as I'm guessing. But the latter don't make sense to me, while the former seems as not the case, because of the single `debugger_compounds` property name.

Could you please elaborate it a bit?

**Comment by daveleroy** [comment]
It should be added to the readme. 

A compound appear in the ui like any configuration and let you start multiple configurations at once.

```jsonc 
{
   "name": "...", // Name of compound which appears in the launch configuration drop down menu.
   "configurations": [ "..."] // Names of configurations that compose this compound configuration
}
```

If you install `LSP-json` you should get auto complete for these

**Comment by yaroslavyaroslav** [comment]
Ok, that's make sense. So why would I need to start multiple configurations simultaneously? @daveleroy

**Comment by daveleroy** [comment]
For most people its probably not needed but developing client + server applications where you want to run and debug both at once or something like Electron which has multiple processes you want to debug at the same time.
