### ISSUE TITLE
How can I add my custom debugger?

### ISSUE THREAD

**Issue by wybryk-ananasa** [daveleroy/SublimeDebugger#233]

**Comment by daveleroy** [comment]
There are tickets that cover adding adapters.

https://github.com/daveleroy/SublimeDebugger/issues/211
https://github.com/daveleroy/SublimeDebugger/issues/191
https://github.com/daveleroy/SublimeDebugger/issues/92

And obviously the adapters which are already supported https://github.com/daveleroy/SublimeDebugger/tree/master/modules/adapters
