### ISSUE TITLE
Toggle breakpoint at right-click position

### ISSUE THREAD

**Issue by kcfnmi** [daveleroy/SublimeDebugger#238]
Currently it toggles the breakpoint at the line the cursor is (editing line).

https://github.com/daveleroy/SublimeDebugger/assets/109356759/9753f067-768f-45ac-b2e4-5fc26df4b997

**Comment by daveleroy** [comment]
I don't this its possible to change this and this is also how other packages like LSP behave

**Comment by predragnikolic** [comment]
I think it is possible to get the x, y positions of the mouse from the `Event` object, if you specify a want_event method in the toggle breakpoint command , see https://www.sublimetext.com/docs/api_reference.html#sublime.Event

**Comment by daveleroy** [comment]
If someone wants to support this they can look into it but I don't have any plans to do it. 

The commands that would use `want_event` would need to support calls with and without the `event` dict since anyone can call the commands directly or from the command palette.
