### ISSUE TITLE
Disable highlight current editing line

### ISSUE THREAD

**Issue by kcfnmi** [daveleroy/SublimeDebugger#239]
Keep only the highlight current debugging line.

Disable highlight current editing line while debugging.

https://github.com/daveleroy/SublimeDebugger/assets/109356759/2b3bc3a9-8bbc-4923-a862-149e68b9f7c5

**Comment by daveleroy** [comment]
The selection is now cleared every time the debugger creates/moves the line selection so there is no highlighted line unless you select a line
