### ISSUE TITLE
Colored ouput

### ISSUE THREAD

**Issue by kcfnmi** [daveleroy/SublimeDebugger#240]
<img width="489" alt="Screenshot 2024-01-08 at 18 14 09" src="https://github.com/daveleroy/SublimeDebugger/assets/109356759/d76be8fb-4d9c-41f2-9101-d783a59bc83e">
<img width="1009" alt="Screenshot 2024-01-08 at 18 18 02" src="https://github.com/daveleroy/SublimeDebugger/assets/109356759/f859a1c1-e72b-49f6-9b7f-177810c6f0d8">

**Comment by daveleroy** [comment]
The console isn't a tty I wouldn't expect this to work
