### ISSUE TITLE
LLDB multi threaded stepping

### ISSUE THREAD

**Issue by druppy** [daveleroy/SublimeDebugger#245]
I have been really happy with my sublime debugger setup for a while, and everything seems to work just fine after some tweeking of keymaps and config setup.

I have, with success been debugging single threaded executables, but when I start debugging multi threaded apps and try to single step in a thread (after successfully  hitting a breakpoint), it jumps over to single steps in other threads too (very confusing and not helpful). As a side note, `gdb` works fine in threaded executables. 

Is this something i have misunderstood or is it a bug in the debugger plugin or is this a bug/feature in `LLDB`  ?

**Comment by daveleroy** [comment]
Are you using what is on package control? There was an issue where stepping was targeting the wrong thread https://github.com/daveleroy/SublimeDebugger/commit/33d1a829db62b0f26dfad51b1272bfc96f8dabb1

**Comment by druppy** [comment]
Yes I am, and it sound that problem. When will this fix go into package control version ?

**Comment by druppy** [comment]
> Are you using what is on package control? There was an issue where stepping was targeting the wrong thread [33d1a82](https://github.com/daveleroy/SublimeDebugger/commit/33d1a829db62b0f26dfad51b1272bfc96f8dabb1) but that is not on package control yet

I tried to clone this git repos from master as suggested to `~/.config/sublime-text/Packages` and the module loads as expected, but I get an `● Failed: No versions to install` error. Are there some essential file that is missing when cloning ?

**Comment by daveleroy** [comment]
The fixes for multi-threaded stepping should be on package control now.  The above issue was probably some issue with master I believe it should clone fine now.
