### ISSUE TITLE
Option to make variables panel wider

### ISSUE THREAD

**Issue by eugenesvk** [daveleroy/SublimeDebugger#247]
Is it possible to make the variables panel take the full width of the screen like Console and Protocol? Othewise it's sometimes too narrow
Thanks

**Comment by daveleroy** [comment]
There is already a ticket for resizing panels https://github.com/daveleroy/SublimeDebugger/issues/231. 

Making the variables panel full width is unlikely to be implemented it would require adding/removing phantoms not just adjusting the size.
