### ISSUE TITLE
`selector` property in task

### ISSUE THREAD

**Issue by AmjadHD** [daveleroy/SublimeDebugger#249]
```json
    "debugger_tasks": [
        {
            "name": "Nim: compile for debugging",
            "shell_cmd": "nim c -g ${file}",
            "selector": "source.nim",
            "file_regex": "^(.+.nim)\\((\\d+), (\\d+)\\) (.*)",
            "line_regex": "Error:"
        }
    ]
```
when running the task, it runs forever (I need to Kill it) and nothing is printed to the output.

**Comment by daveleroy** [comment]
If you add anything not supported by terminus like `selector` its going to throw an exception when running the command that ends up in the sublime console. Detecting that error isn't possible right now.

You can click on the icon in the tab to kill the task.
