### ISSUE TITLE
{command_pick_process} not implemented.

### ISSUE THREAD

**Issue by yaroslavyaroslav** [daveleroy/SublimeDebugger#252]
This line https://github.com/daveleroy/SublimeDebugger/blob/805614b704da4f61f11fefcc13a833de25cad229/modules/adapters/lldb.py#L91 points to a module that doesn't exist, so on a call with `command_pick_process` app silently dies.

I see that it was changed in this 88d63daafc8ddd804dba7a083d6a72a7a1898d4a commit, but I don't see a related changes made in `./utils` neither am I able to launch a previous stable version locally, because it fails to install any adapter due to some Settings error while being installed by the repo clone, neither I'm able to fix it just by calling the old function `process_select()`, because it occurs broken as well.

Is there a way how I can overcome this?

**Comment by daveleroy** [comment]
You have to specify the pid manually. Dependencies aren't supported on the 3.8 plugin host so anything using psutil is broken until dependencies work on 3.8

**Comment by yaroslavyaroslav** [comment]
@daveleroy got it thanks, just in case maybe do you know any way to put a pid there dynamically? My use case is iOS one, and I got a pid in return of install command run. Have no clue how to put it there though.

**Comment by daveleroy** [comment]
Can you not just attach with the program name?

**Comment by yaroslavyaroslav** [comment]
Yep, but I can't pass the name to Debugger, it throws "pid should be an integer" error.

**Comment by daveleroy** [comment]
Use the `program` field and don't specify the pid https://github.com/vadimcn/codelldb/blob/master/MANUAL.md#attaching-to-a-running-process

**Comment by yaroslavyaroslav** [comment]
Yep, that worked. Thanks.
