### ISSUE TITLE
Debugger broke and now I cannot install any adapter

### ISSUE THREAD

**Issue by spirosbond** [daveleroy/SublimeDebugger#254]
My debugger stopped working and now I cannot install any adapter anymore... I think it is linked with the last update. Any ideas?

I tried reinstalling the package, rebooting laptop and trying with different project.

![Screenshot_20240324_144309](https://github.com/daveleroy/SublimeDebugger/assets/1714848/f6456390-c4be-4cd0-94a3-dc905494643c)
![Screenshot_20240324_144343](https://github.com/daveleroy/SublimeDebugger/assets/1714848/e08d1a3c-c43e-4cb1-9c34-11731ba83415)

**Comment by d0sse** [comment]
I've got the same problem
<img width="460" alt="Screenshot 2024-03-24 at 18 07 16" src="https://github.com/daveleroy/SublimeDebugger/assets/16508608/03da9928-c5ff-40ac-9d4c-ae4cae830d1f">

**Comment by daveleroy** [comment]
I believe this should be fixed now

**Comment by spirosbond** [comment]
Yup, i confirm it works for me now. Thank you for the quick resolution!

**Comment by d0sse** [comment]
Now works, thanks!
