### ISSUE TITLE
Does it work without terminus ?

### ISSUE THREAD

**Issue by AmjadHD** [daveleroy/SublimeDebugger#258]
No matter what value of "terminal" or "console", I can't run my task without terminus.
OS: Windows 10.

**Comment by daveleroy** [comment]
Tasks always use terminus. 

The preference `external_terminal` controls what terminal is used when a debug adapter requests an `external` terminal and that defaults to terminus as well.

https://github.com/daveleroy/SublimeDebugger/blob/master/modules/terminal_external.py has implementations for a select few but they are not really tested so you might need to contribute changes to get them working or add new ones if you want to support other terminals

**Comment by dbrignoli** [comment]
FYI, in my experience, setting `"console"` to `"internalConsole"` avoids the dependency on Terminus.
