### ISSUE TITLE
Point to LLVM official LLDB DAP plugin

### ISSUE THREAD

**Issue by medismailben** [daveleroy/SublimeDebugger#262]
This should point to the new LLVM official LLDB DAP plugin: https://github.com/llvm/llvm-project/tree/main/lldb/tools/lldb-dap

**Comment by medismailben** [comment]
https://marketplace.visualstudio.com/items?itemName=llvm-vs-code-extensions.lldb-dap

**Comment by daveleroy** [comment]
This project doesn't support `lldb-dap`. If someone wants to add support for it they are welcome to but I don't see the need for me to spend the time on it when codelldb works well.
