### ISSUE TITLE
[FR] Make code subwindow active on cursor change

### ISSUE THREAD

**Issue by DJManas** [daveleroy/SublimeDebugger#265]
Hello,

just a little question. Would it be possible to add feature to make window code active upon debugging cursor change?

E.g. I launch step_over like on this picture, it seems I am on line 123
![image](https://github.com/daveleroy/SublimeDebugger/assets/2048276/f2350715-c279-4365-a4be-6b9a85204a5e)

I want to add breakpoint using shortcut, but its not doing it I have to click into the code window and press the key again.

Not sure if anyone else would appreciate this so if it can and will be implemented, best way would be to add option to turn it on/off.

Thanks,
Regards,
Petr Sourek

**Comment by daveleroy** [comment]
Clearing the curser is intended here since if you have settings like `highlight_line` it can cause issues.

**Comment by DJManas** [comment]
> Clearing the curser is intended here since if you have settings like `highlight_line` it can cause issues.

So if I I get it correctly. When I disable `highlight_line` the code window won't loose focus on stepping through code?
