### ISSUE TITLE
Debugger tab ui disappearing

### ISSUE THREAD

**Issue by SomedudeX** [daveleroy/SublimeDebugger#266]
When you scroll down in the debugger panel, the tab buttons disappear. The clip attached below demonstrates this issue:

https://github.com/daveleroy/SublimeDebugger/assets/101906945/fd074a1b-ab07-4736-802f-f9a4aedb8fb5

**Comment by daveleroy** [comment]
They have to disappear when scrolling because the ui cannot be redrawn every frame
