### ISSUE TITLE
How to add keyboard shortcuts for debug actions?

### ISSUE THREAD

**Issue by ilmoralito** [daveleroy/SublimeDebugger#267]
I would like to add keyboard shortcuts to debugging actions. For example `F5` for Continue or Pause, `F10` for Step over. Similar to the ready actions in https://code.visualstudio.com/docs/editor/debugging#_debug-actions

Could you tell me how to achieve this? Greetings and thanks in advance

**Comment by daveleroy** [comment]
This should help you https://github.com/daveleroy/SublimeDebugger/issues/222

**Comment by ilmoralito** [comment]
> This should help you #222

Thanks for commenting. I'll take a look.

**Comment by daveleroy** [comment]
Run them from the command palette or just look at the menu files such as contributes/Commands/Default.sublime-commands

**Comment by ilmoralito** [comment]
Thank you. I got the information from here `contributes/Commands/Default.sublime-commands`

Here is my current configuration in case it is a guide for someone

`[
	{
		"keys": ["ctrl+alt+shift+d"],
		"command": "debugger",
		"args": {
			"action": "open"
		}
	},
	{
		"keys": ["ctrl+alt+shift+b"],
		"command": "debugger",
		"args": {
			"action": "toggle_breakpoint"
		}
	},
	{
		"keys": ["f9"],
		"command": "debugger",
		"args": {
			"action": "continue"
		},
	},
	{
		"keys": ["f10"],
		"command": "debugger",
		"args": {
			"action": "step_over"
		}
	},
	{
		"keys": ["f11"],
		"command": "debugger",
		"args": {
			"action": "step_in"
		},
	},
	{
		"keys": ["shift+f11"],
		"command": "debugger",
		"args": {
			"action": "step_out"
		},
	}
],`

Could you clarify what to do where you mention `Run them from the command palette`

**Comment by daveleroy** [comment]
All the commands in that file are accessible through the command palette with the prefix `Debugger:`. If you were logging commands running the command from the command palette would show up in the console.
