### ISSUE TITLE
How to CA Certificates for when downloading adapters?

### ISSUE THREAD

**Issue by tomdaley92** [daveleroy/SublimeDebugger#269]
![Screenshot 2024-07-02 at 12 58 26 PM](https://github.com/daveleroy/SublimeDebugger/assets/12147036/cf9f3b95-3905-4f88-a940-600d79c67e8c)

Currently Unable to download Any adapters as I'm getting self-signed certificate error due to my Netskope client (MITM) on my work machine. It doesn't seem like this debugger uses the custom user CA bundle as I'm supplying the bundle with the private CA roots.

Is there a way to configure this package to use/honor the sublime user ca bundle? Or is there a way to toggle ssl verification for the adapters download?

Thank you!

**Comment by daveleroy** [comment]
No there is not and looking at package control it doesn't seem that trivial to support what you are asking. If you or someone else wants to support self-signed certificates like package control you can open a pull request for it. The logic for performing network requests is here https://github.com/daveleroy/SublimeDebugger/blob/master/modules/adapters/util/request.py.

Disabling ssl verification isn't something I am willing to expose in a setting but you are free to modify the implementation yourself.
