### ISSUE TITLE
debugpy adapter installation fails

### ISSUE THREAD

**Issue by cwjohnson42** [daveleroy/SublimeDebugger#272]
My attempts to install the debugpy adapter resulted in the error message `TypeError: list indices must be integers or slices, not str`. After poking around, I figured out that the problem was in `modules/adapters/python.py` on line 19. It seems that the structure of `debugpy_info` has changed and now the value of `debugpy_info['any']` is a `list` not a `dict`:

```
{
  "any": [
    {
      "hash": {
        "sha256": "57b00de1c8d2c84a61b90880f7e5b6deaf4c312ecbde3a0e8912f2a56c4ac9ae"
      },
      "url": "https://files.pythonhosted.org/packages/51/b1/a0866521c71a6ae3d3ca320e74835163a4671b1367ba360a55a0a51e5a91/debugpy-1.8.7-py2.py3-none-any.whl"
    }
  ],
...
```

I was able to fix the error by replacing the line with

```
await util.request.download_and_extract_zip(debugpy_info['any'][0]['url'], f'{path}/debugpy', log=log)
```

but that may not be the best permanent solution.

**Comment by 8Observer8** [comment]
@cwjohnson42 hello. It was fixed: https://github.com/daveleroy/SublimeDebugger/issues/285
