### ISSUE TITLE
The plugin requires you to recreate the project each time you use it

### ISSUE THREAD

**Issue by Cheng-MaoMao** [daveleroy/SublimeDebugger#276]
I'm using this plugin to debug python programs.First use I have created the files needed for debugging.But I was prompted to start debugging after reopening Sublime. Debugger requires a sublime project. Would you like to create a new sublime project?

Is this normal? Or am I missing that step?

![image](https://github.com/user-attachments/assets/53c683ba-27e1-4eeb-9365-d82589bdf348)

**This is the file I created**

![image](https://github.com/user-attachments/assets/abd3628d-aa2b-4beb-981b-4b55e6b1d492)

**Comment by daveleroy** [comment]
You need to open the project either from the project files or from `Open` in the `Project` menu of sublime you have probably opened the folder.

Or install https://github.com/SublimeText/AutoProjects and it will automatically open the project when you open a folder with a project file in it
