### ISSUE TITLE
I can't resolve "Failed: list indices must be integers or slices, not str". What should I do?

### ISSUE THREAD

**Issue by takkii** [daveleroy/SublimeDebugger#283]
I want to solve this so that I can debug python code with debugpy.

Step in, step out, etc. are disabled when I place the cursor over them.

What should I do?

#### Operating environment

- Windows 11 Home 24H2
-  use Scoop
-  Python 3.13.1

> project_name.sublime-project 

```json
{
	"folders":
	[
		{
			"path": ".",
		}
	],
	"debugger_configurations":
	[
        {
            "name": "Python Debugger: Attach remote debug.",
            "type": "python",
            "request": "attach",
            "connect": {
                "host": "localhost",
                "port": 5678
            }
        },
        {
            "name" : "Python Debugger: Attach using process Id",
            "type" : "python",
            "request" : "attach",
            "selector": "source.python | text.html.python",
            "debugServer": 5678,
            "processId": "3108",
            "pathMappings": [{
                "localRoot": "${workspaceFolder}",
                "remoteRoot": "."
            }]
        },
        {
            "name": "Python Debugger: Current File",
            "type": "sublime",
            "platform": "windows",
            "request": "launch",
            "selector": "source.python | text.html.python",
            "program": "\\${file}",
            "console": "integratedTerminal",
        },
	],
}
```
![windows_diarog](https://github.com/user-attachments/assets/d8574b9a-5e56-4a01-9224-2cab04a93622)
![windows_error](https://github.com/user-attachments/assets/6a3b84a2-f4a7-449c-88f6-6f004200c27c)

**Comment by takkii** [comment]
_I solved it myself. Thank you._

**Comment by takkii** [comment]
#### This is the resolved configuration [file](https://github.com/takkii/PythonSettings/tree/main)

- You can use debugpy from Sublime Debugger on Windows11/ WSL2.

**Comment by takkii** [comment]
#### We are currently consulting with maintainers.

**Comment by 8Observer8** [comment]
@takkii hello. Could you write what should I add to the project file to fix this error?

```
{
	"folders": [
		{
			"path": ".",
		},
	],
	"debugger_configurations": [
		{
			"name": "Python",
			"type": "python",
			"request": "launch",
			"program": "${project_path}/main.py"
		}
	],
}
```

**Comment by takkii** [comment]
> hello. Could you write, please, what should I add to the project file to fix this error?

Thank you for your message.

I'm using SublimeText on Windows.

I don't have a UNIX environment right now so I'm using WSL.

"type": "python", → "type": "sublime",

"request": "launch"

For launch, it's better not to set type to python.

When you start, the following message will be displayed, but launch will work.

> `linked_packages` is empty no packages will be symlinked for debugging purposes.

```json
{
	"folders":
	[
		{
			"path": ".",
		}
	],
	"debugger_configurations":
	[
	{
            "name": "Python Debugger: Current File",
            "type": "sublime",
            //"platform": "windows",
            "request": "launch",
            "selector": "source.python | text.html.python",
            "program": "\\${file}",
            "console": "integratedTerminal",
	}
	],
},
```

**Comment by daveleroy** [comment]
This should be fixed just make sure you have the latest version from package control

**Comment by 8Observer8** [comment]
@daveleroy 
> This should be fixed just make sure you have the latest version from package control

I confirm it. I've installed the stable 4188 and updated the Debugger:
- `Tools` > `Debugger` > `Open`

![image](https://github.com/user-attachments/assets/810e346f-a1db-4c16-9d95-80f2fc4ecfb6)

![image](https://github.com/user-attachments/assets/e865d6ce-aef4-461d-b8f7-dbb47d70ee05)

![image](https://github.com/user-attachments/assets/8f3fd9dc-1f9f-4ea7-8cdc-633bd04f5e0b)

It is even works work this project configuration that I did not change:

```
{
	"folders": [
		{
			"path": ".",
		},
	],
	"debugger_configurations": [
		{
			"name": "Python",
			"type": "python",
			"request": "launch",
			"program": "${project_path}/main.py"
		}
	],
}
```

I can set a breakpoint by RMB:

![image](https://github.com/user-attachments/assets/c34e77fb-ebdc-4dab-934b-ab348224f2b4)

I run the debugging and it stops on breakpoints. `Locals` and `Watch`. It is great! Thank you very much!

**Comment by 8Observer8** [comment]
@daveleroy can I use this debugger for CMake (C, C++) and Node.js (JavaScript)?

**Comment by takkii** [comment]
@8Observer8

- You can choose not to explicitly specify debugpy or configure a config file, but I don't recommend it.
