### ISSUE TITLE
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by 8Observer8** [daveleroy/SublimeDebugger#285]
Sublime Text 4 v4113

Traceback (most recent call last):
  File "C:\Users\8Observer8\AppData\Roaming\Sublime Text\Packages\Debugger\modules\debugger.py", line 69, in get
    instance = Debugger(window, skip_project_check=skip_project_check)
  File "C:\Users\8Observer8\AppData\Roaming\Sublime Text\Packages\Debugger\modules\debugger.py", line 118, in __init__
    self.console: ConsoleOutputPanel = ConsoleOutputPanel(self)
  File "C:\Users\8Observer8\AppData\Roaming\Sublime Text\Packages\Debugger\modules\console.py", line 22, in __init__
    super().__init__(debugger, 'Debugger Console', name='Console', show_tabs=True, remove_last_newline=True)
  File "C:\Users\8Observer8\AppData\Roaming\Sublime Text\Packages\Debugger\modules\output_panel.py", line 137, in __init__
    scaled_font = settings.get('font_size', 12) * (Settings.minimum_console_height + 1.75) / 5
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

**Comment by daveleroy** [comment]
You should update Sublime Text. I believe this is a bug with the sublime text api and was fixed in build 4170.

`API: Fixed Settings.get not always returning the default value on failure` see https://www.sublimetext.com/dev

**Comment by 8Observer8** [comment]
@daveleroy I have installed the latest ST4 v4190. Could you help me to start with Python 3.12? I created a new project:

```json
{
	"folders": [
		{
			"path": ".",
		},
	],
	"debugger_configurations": [
		{
			"name": "Python",
			"type": "python",
			"request": "launch",
			"program": "${project_path}/main.py"
		}
	],
}
```

I pressed `Toos` > `Debugger` > `Open`:

![image](https://github.com/user-attachments/assets/5dbf6250-ee78-4854-9afa-4a80e0060482)

**Comment by daveleroy** [comment]
This was just fixed last night so you probably need to update the Debugger package now.

https://github.com/daveleroy/SublimeDebugger/issues/283
