### ISSUE TITLE
Adapters removed on update

### ISSUE THREAD

**Issue by rchl** [daveleroy/SublimeDebugger#63]
I haven't verified that but I think that installed adapters are removed on upgrading to a new version of `Debugger`.

If that's the case then I suppose it's because package control removes old package before installing new version.

`Debugger` should instead ship in packaged form and install adapters in ST's Cache directory. Here is how we do it for LSP-* packages - https://github.com/sublimelsp/lsp_utils/blob/cd41e4277982d7c4f104c64e5727989e1cd44398/st3/lsp_utils/server_npm_resource.py#L66-L94

**Comment by rwols** [comment]
This is now moving to dumping data in `sublime.cache_path()/../Package Storage` (or some variation on that) due to ST scanning package folders for resources.

**Comment by daveleroy** [comment]
`Package Storage/Debugger` is now used as the location for installing adapters
